// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS (adapted for multi-platform) */

let nativeBinding = null;
let loadError = null;
const {
  platform,
  arch
} = process;
try {
  if (platform === "darwin") {
    if (arch === "arm64") {
      nativeBinding = __webpack_require__("../merkle-tree/merkle-tree-napi.darwin-arm64.node");
    } else if (arch === "x64") {
      nativeBinding = __webpack_require__(Object(function webpackMissingModule() {
        var e = new Error("Cannot find module './merkle-tree-napi.darwin-x64.node'");
        e.code = 'MODULE_NOT_FOUND';
        throw e;
      }()));
    } else {
      throw new Error(`Unsupported macOS architecture: ${arch}`);
    }
  } else if (platform === "linux") {
    if (arch === "x64") {
      nativeBinding = __webpack_require__(Object(function webpackMissingModule() {
        var e = new Error("Cannot find module './merkle-tree-napi.linux-x64-gnu.node'");
        e.code = 'MODULE_NOT_FOUND';
        throw e;
      }()));
    } else if (arch === "arm64") {
      nativeBinding = __webpack_require__(Object(function webpackMissingModule() {
        var e = new Error("Cannot find module './merkle-tree-napi.linux-arm64-gnu.node'");
        e.code = 'MODULE_NOT_FOUND';
        throw e;
      }()));
    } else {
      throw new Error(`Unsupported Linux architecture: ${arch}`);
    }
  } else if (platform === "win32") {
    if (arch === "x64") {
      nativeBinding = __webpack_require__(Object(function webpackMissingModule() {
        var e = new Error("Cannot find module './merkle-tree-napi.win32-x64-msvc.node'");
        e.code = 'MODULE_NOT_FOUND';
        throw e;
      }()));
    } else if (arch === "arm64") {
      nativeBinding = __webpack_require__(Object(function webpackMissingModule() {
        var e = new Error("Cannot find module './merkle-tree-napi.win32-arm64-msvc.node'");
        e.code = 'MODULE_NOT_FOUND';
        throw e;
      }()));
    } else {
      throw new Error(`Unsupported Windows architecture: ${arch}`);
    }
  } else {
    throw new Error(`Unsupported platform: ${platform}`);
  }
} catch (err) {
  loadError = err;
}
if (!nativeBinding) {
  const expectedNames = {
    "darwin-arm64": "merkle-tree-napi.darwin-arm64.node",
    "darwin-x64": "merkle-tree-napi.darwin-x64.node",
    "linux-x64": "merkle-tree-napi.linux-x64-gnu.node",
    "linux-arm64": "merkle-tree-napi.linux-arm64-gnu.node",
    "win32-x64": "merkle-tree-napi.win32-x64-msvc.node",
    "win32-arm64": "merkle-tree-napi.win32-arm64-msvc.node"
  };
  const key = `${platform}-${arch}`;
  const hint = expectedNames[key] ? ` (expected: ./${expectedNames[key]})` : "";
  const message = `Failed to load native binding for ${platform}/${arch}${hint}\nOriginal error: ${loadError && loadError.stack ? loadError.stack : loadError}`;
  throw new Error(message);
}
module.exports = nativeBinding;
module.exports.MerkleClient = nativeBinding.MerkleClient;
module.exports.MULTI_ROOT_ABSOLUTE_PATH = nativeBinding.MULTI_ROOT_ABSOLUTE_PATH;

/***/